- name: "manage worker1 and 2"
  hosts: all
  become: true
  tasks:
  - name: "ensure Amit user exists"
    user:
      name: amit
      state: present
  - name: "ensure Alex user exists"
    user:
      name: alex
      state: present
   - name: "ensure Imran user exists"
     user:
       name: Imran
       state: present
